apiVersion: v2
name: wg-easy
description: Using the offical wg-easy/wg-easy image with almost any environment variables for K8s. Supporting Init Mode.
type: application
version: 0.3.0
appVersion: 15.1.0
icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wg-easy/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wg-easy
    - name: Offical wg-easy Documentation
      url: https://wg-easy.github.io/wg-easy/latest/
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: added
      description: "Registry value added. Added functionality to _helpers.tpl to support it."
    - kind: changed
      description: "Better comments for documentation in values.yaml."
    - kind: added
      description: "Added missing values in values.schema.yaml."
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wg-easy
      image: ghcr.io/wg-easy/wg-easy:15.1.0
keywords:
  - wireguard
  - vpn
  - wg-easy
