wordpress:
  init:
    enabled: true
    existingSecret: "wordpress-test-secret"
    firstname: "John"
    lastname: "Doe"
    title: "John Does's Blog"
  language: "de_DE"
  plugins:
    - name: "two-factor"
      activate: true
      autoupdate: true
    - name: "blocksy-companion"
      activate: true
      autoupdate: true
    - name: "generateblocks"
      activate: true
      autoupdate: true
    - name: "cache-enabler"
      activate: true
      autoupdate: true
    - name: "redis-cache"
      activate: true
      autoupdate: true
    - name: "autoptimize"
      activate: true
      autoupdate: true
    - name: "stackable-ultimate-gutenberg-blocks"
      activate: true
      autoupdate: true
    - name: "manage-notification-emails"
      activate: true
      autoupdate: true
  themes:
    - name: "blocksy"
      activate: false
      autoupdate: true
    - name: "https://creativethemes.com/downloads/blocksy-child.zip"
      slug: "blocksy-child"
      activate: true
      autoupdate: true
  users:
    - username: "johnsmith"
      email: "john.smith@example.com"
      displayname: "John Smith"
      firstname: "John"
      lastname: "Smith"
      role: "contributor"
      sendEmail: false
  configExtraSecret:
    name: "wordpress-test-secret"
  htaccessConfigMap: "wordpress-custom-config"
  url: "http://192.168.178.31:30111"
service:
  nodePorts:
    http: 30111
storage:
  resourcePolicy: "" # Delete PVC on helm uninstall
apache:
  customPhpConfigMap: "wordpress-custom-config"
metrics:
  wordpress:
    enabled: true
    serviceMonitor:
      existingSecret: "wordpress-test-secret"
    grafanaDashboard:
      enabled: true
      namespace: "monitoring"
  apache:
    enabled: true
mariadb:
  auth:
    database: "wordpress_db"
    username: "wordpress_db_user"
    existingSecret: "wordpress-test-secret"
redis:
  enabled: true
  createConfig: true
  # Optional: Redis authentication
  # auth:
  #   password: "your-redis-password"
  # Optional: Redis Object Cache scaling
  # scaling:
  #   type: "replication"
  #   servers:
  #     - "tcp://redis-0.redis:6379?database=0&role=master"
  #     - "tcp://redis-1.redis:6379?database=0&alias=replica-01"
  #
  # Sentinel example:
  # scaling:
  #   type: "sentinel"
  #   sentinel: "mymaster"
  #   servers:
  #     - "tcp://redis-sentinel-0.redis-sentinel:26379"
  #     - "tcp://redis-sentinel-1.redis-sentinel:26379"
