apiVersion: v2
name: wireguard
description: "Using the offical linuxserver/wireguard image with almost any environment variables for K8S. Supporting server and client mode."
type: application
version: 0.3.8
appVersion: 1.0.20250521-r1-ls101 # renovate: image=docker.io/linuxserver/wireguard
icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wireguard/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wireguard
    - name: Offical WireGuard Repository
      url: https://github.com/linuxserver/docker-wireguard
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: changed
      description: "Update docker.io/linuxserver/wireguard to ([source](https://redirect.github.com/linuxserver/docker-wireguard))"
      links:
        - name: Pull Request
          url: https://github.com/slydlake/helm-charts/pull/124
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wireguard
      image: docker.io/linuxserver/wireguard:1.0.20250521-r1-ls101
keywords:
  - wireguard
  - vpn
  - linuxserver
